name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag="gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-app \
          --image="gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app" \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated
