name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit application --tag gcr.io/zippy-pad-442508-s9/python-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy application --tag gcr.io/zippy-pad-442508-s9/python-app --region europe-west1 --platform managed
