name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Copy files to GCS bucket
      run: |
        # Copier le Dockerfile vers le bucket
        gsutil cp Dockerfile gs://bucket-gcp-ctp/
        # Copier tout le contenu du répertoire
        gsutil -m cp -r . gs://bucket-gcp-ctp/source/

    - name: Build from GCS bucket
      run: |
        gcloud builds submit gs://bucket-gcp-ctp --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app \
          --region europe-west1 \
          --platform managed
