name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Debug - List files
      run: |
        pwd
        ls -la
        echo "Current directory contents:"
        find . -type f

    - name: Copy files to GCS bucket
      run: |
        gsutil cp ./Dockerfile gs://bucket-gcp-ctp/
        gsutil cp ./main.py gs://bucket-gcp-ctp/
        gsutil cp ./requirements.txt gs://bucket-gcp-ctp/

    - name: Build from GCS bucket
      run: |
        gcloud builds submit gs://bucket-gcp-ctp \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated
